### ISSUE TITLE
the requested PHP extension intl is missing from your system

### ISSUE THREAD

**Issue by Zt-freak** [Limenius/symfony-react-sandbox#65]
Hello, I'm not that good with PHP and I've tried searching for a solution, but it seems I can't figure it out. If you have time, could you please help me out, thank you <3.

When I `composer install` I get the following message:
```
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Installation request for league/uri 5.3.0 -> satisfiable by league/uri[5.3.0].
    - league/uri 5.3.0 requires ext-intl * -> the requested PHP extension intl is missing from your system.
  Problem 2
    - Installation request for league/uri-components 1.8.2 -> satisfiable by league/uri-components[1.8.2].
    - league/uri-components 1.8.2 requires ext-intl * -> the requested PHP extension intl is missing from your system.
  Problem 3
    - Installation request for league/uri-hostname-parser 1.1.1 -> satisfiable by league/uri-hostname-parser[1.1.1].
  Problem 4
    - Installation request for league/uri-manipulations 1.5.0 -> satisfiable by league/uri-manipulations[1.5.0].
    - league/uri-manipulations 1.5.0 requires ext-intl * -> the requested PHP extension intl is missing from your system.

  To enable extensions, verify that they are enabled in your .ini files:
    - C:\xampp\php\php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
```

**Comment by MateoWartelle** [comment]
Not ideal, but was getting the same error and was able to get it running with 

`composer install --ignore-platform-reqs`

**Comment by Zt-freak** [comment]
o thanks, it works!

**Comment by jdreesen** [comment]
The solution is named in the message:
>\- league/uri 5.3.0 requires **ext-intl * -> the requested PHP extension intl is missing from your system.**
>
>To enable extensions, verify that they are enabled in your .ini files:
>\- C:\xampp\php\php.ini

You have to modify this file `C:\xampp\php\php.ini` to enable the needed extension.
There should be the following line `;extension=php_intl.dll` (somewhere in the middle of the file). Remove the leading `;` to enable the extension. Then it should install.

`--ignore-platform-reqs` is **dangerous** (if you don't know what you're doing), because it installs the packages whether your PHP supports them or not - this will result in runtime errors when one of the missing dependencies gets called!

**Comment by Zt-freak** [comment]
thanks, I'll be using that.
